# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: "agingorange's crkbd miryoku build"
on:
  - workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      keyboard: '["crkbd"]'
